### ISSUE TITLE
Does not work on 1.9 --> public_send

### ISSUE THREAD

**Issue by grosser** [kern/minitest-reporters#38]
```
/Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-reporters-0.12.0/lib/minitest/reporter_runner.rb:76:in `trigger_callback': undefined method `public_send' for #<MiniTest::Reporters::DefaultReporter:0x10509cb70> (NoMethodError)
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-reporters-0.12.0/lib/minitest/reporter_runner.rb:75:in `each'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-reporters-0.12.0/lib/minitest/reporter_runner.rb:75:in `trigger_callback'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-reporters-0.12.0/lib/minitest/reporter_runner.rb:24:in `_run_suites'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-3.3.0/lib/minitest/unit.rb:778:in `_run_anything'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-3.3.0/lib/minitest/unit.rb:967:in `run_tests'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-3.3.0/lib/minitest/unit.rb:954:in `send'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-3.3.0/lib/minitest/unit.rb:954:in `_run'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-3.3.0/lib/minitest/unit.rb:953:in `each'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-3.3.0/lib/minitest/unit.rb:953:in `_run'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-3.3.0/lib/minitest/unit.rb:942:in `run'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02/gems/minitest-3.3.0/lib/minitest/unit.rb:700:in `autorun'
    from /Users/mgrosser/.rvm/gems/ree-1.8.7-2012.02@global/gems/rake-0.9.2.2/lib/rake/rake_test_loader.rb:21
```
