### ISSUE TITLE
Empty test suite error running tests inside Rubymine since upgrade to 1.1.0

### ISSUE THREAD

**Issue by dmagliola** [kern/minitest-reporters#176]
Since upgrading to minitest-reporters 1.1.0 (from 1.0.20), when I run tests inside Rubymine, I get an "Empty test suite" error.

Running tests inside Rubymine worked well in 1.0.20
And "rake test" from the command line still works well in 1.1.0, it's just Rubymine somehow.

Full Rubymine console output:

```` 
/Users/daniel/.rvm/rubies/ruby-2.1.5/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) -Itest /Applications/RubyMine.app/Contents/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb
Testing started at 18:47 ...
Work directory: /Users/daniel/Documents/xxxx/code/xxxx
 
87 test scripts were detected:
=========================================
1. (censored, sorry)
2. (...)
87. (...)
=========================================
Command line: 
["/Users/daniel/.rvm/rubies/ruby-2.1.5/bin/ruby", "-e", "$stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift)", "-Itest", "/Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/bin/zeus", "test", "/Users/daniel/Documents/xxxx/code/xxx/test/controllers/api/app_sessions_controller_test.rb", "(... a lot more files here ...)"]
/Users/daniel/.rvm/rubies/ruby-2.1.5/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) -Itest /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/bin/zeus test /Users/daniel/Documents/xxxx/code/xxx/test/controllers/api/app_sessions_controller_test.rb (... again, a lot more files here ...)
Started

/Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-reporters-1.1.0/lib/minitest/reporters/rubymine_reporter.rb:82:in `before_suite': undefined method `create_suite_started' for nil:NilClass (NoMethodError)
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-reporters-1.1.0/lib/minitest/reporters/base_reporter.rb:20:in `before_test'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-reporters-1.1.0/lib/minitest/reporters/rubymine_reporter.rb:90:in `before_test'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-reporters-1.1.0/lib/minitest/reporters.rb:46:in `block in run_with_hooks'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-reporters-1.1.0/lib/minitest/reporters.rb:46:in `each'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-reporters-1.1.0/lib/minitest/reporters.rb:46:in `run_with_hooks'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:781:in `run_one_method'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:308:in `run_one_method'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:296:in `block (2 levels) in run'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:295:in `each'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:295:in `block in run'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:334:in `on_signal'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:321:in `with_info_handler'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:294:in `run'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:155:in `block in __run'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:155:in `map'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:155:in `__run'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/minitest-5.8.0/lib/minitest.rb:129:in `run'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/zeus-0.15.3/lib/zeus/m.rb:201:in `execute'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/zeus-0.15.3/lib/zeus/m.rb:121:in `run'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/zeus-0.15.3/lib/zeus/m.rb:106:in `run'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/zeus-0.15.3/lib/zeus/rails.rb:214:in `test'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/zeus-0.15.3/lib/zeus.rb:148:in `block in command'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/zeus-0.15.3/lib/zeus.rb:135:in `fork'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/zeus-0.15.3/lib/zeus.rb:135:in `command'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/zeus-0.15.3/lib/zeus.rb:50:in `go'
	from -e:1:in `<main>'
Coverage report generated for MiniTest to /Users/daniel/Documents/xxxx/code/xxxx/coverage. 34 / 101 LOC (33.66%) covered.
================================================================================
Code coverage is less than 100%!
================================================================================
Coverage (33.66%) is below the expected minimum coverage (100.00%).
/Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (2): [/Users/daniel/.rvm/rubies/ruby-2.1.5/bin/r...] (RuntimeError)
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
	from /Users/daniel/.rvm/gems/ruby-2.1.5@xxxx/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
	from /Applications/RubyMine.app/Contents/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:103:in `drb_launch_tests'
	from /Applications/RubyMine.app/Contents/rb/testing/runner/tunit_or_minitest_in_folder_runner.rb:137:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
Empty test suite.

````

Thanks!

**Comment by os97673** [comment]
Is this reproducible with any test suite?

**Comment by os97673** [comment]
it looks like a duplicate of #175.  Please answer my question there.
